package meet.patient.dto;

public enum Disease {
    ISCHEMIC_HEART_DISEASE,
    STROKE,
    LOWER_RESPIRATORY_INFECTIONS,
    CHRONIC_OBSTRUCTIVE_PULMONARY,
    TRACHEA_CANCER,
    BRONCHUS_CANCER,
    LUNG_CANCER,
    DIABETES_MELLITUS,
    ALZHEIMER,
    DEHYDRATION,
    TUBERCULOSIS,
    CIRRHOSIS,
    ADHD,
    ALICE_IN_WONDERLAND_SYNDROM,
    SYNESTHESIA,
    NARCOLEPSY,
    UNER_TAN_SYNDROM,
    AWIOFOBIA,
    KALIGYNEOFOBIA
}
